"use client";
import Image,{type StaticImageData}from"next/image";
import{useEffect,useState}from"react";
import logoJp from"../public/Logo/Logo.jpeg";
import logoAna from"../public/Logo/Logo - Anadias_Terapeuta.jpeg";
import logoCabanas from"../public/Logo/Logo-Cabanas_do_Rio.png";
import logoBrava from"../public/Logo/Logo - Brava_Spa_Urbano.png";
import logoInjoy from"../public/Logo/Logo - Injoy.jpeg";
import logoAtlas from"../public/Logo/atlas-presenca.jpg";
const whatsappUrl="https://wa.me/5548996656319?text=Ol%C3%A1%2C%20JPCreative!%20Quero%20conversar%20sobre%20um%20projeto.";
type Project={name:string;type:string;text:string;url:string;image:StaticImageData;tone:string};
const projects:Project[]=[
 {name:"Ana Dias Reflexoterapia",type:"Site institucional",text:"Cuidado e clareza para apresentar um trabalho terapêutico.",url:"https://anadiasreflexoterapia.com.br",image:logoAna,tone:"ana"},
 {name:"Cabanas do Rio",type:"Hospedagem",text:"Uma presença que aproxima natureza, experiência e reserva.",url:"https://cabanasdorio.com.br",image:logoCabanas,tone:"cabanas"},
 {name:"Brava Spa Urbano",type:"Experiência de marca",text:"Sofisticação e bem-estar traduzidos para o ambiente digital.",url:"https://brava-spa.vercel.app",image:logoBrava,tone:"brava"},
 {name:"Injoy Tau",type:"Landing page",text:"Uma jornada delicada, objetiva e orientada ao contato.",url:"https://injoy-tau.vercel.app",image:logoInjoy,tone:"injoy"}];
const capabilities=[["bi-window","Sites","Presença profissional para representar sua empresa e gerar confiança."],["bi-braces","Sistemas","Ferramentas digitais para organizar e simplificar processos."],["bi-layers","Soluções digitais","Projetos personalizados para necessidades que não cabem em modelos prontos."]];
function Brand({small=false}:{small?:boolean}){return <span className={"official-brand "+(small?"small":"")}><Image src={logoJp} alt="JPCreative" priority sizes={small?"140px":"190px"}/></span>}
function Label({children}:{children:React.ReactNode}){return <p className="section-label"><i className="bi bi-dash-lg"/>{children}</p>}
export default function Home(){
 const[menuOpen,setMenuOpen]=useState(false);const[scrolled,setScrolled]=useState(false);
 useEffect(()=>{const onScroll=()=>setScrolled(scrollY>20);onScroll();addEventListener("scroll",onScroll,{passive:true});return()=>removeEventListener("scroll",onScroll)},[]);
 return <main>
  <header className={"site-header "+(scrolled?"is-scrolled":"")}><div className="nav-shell"><a className="brand" href="#inicio" aria-label="JPCreative — início"><Brand small/></a><nav id="navigation" className={menuOpen?"is-open":""} aria-label="Navegação principal"><a href="#servicos" onClick={()=>setMenuOpen(false)}>Serviços</a><a href="#projetos" onClick={()=>setMenuOpen(false)}>Projetos</a><a href="#processo" onClick={()=>setMenuOpen(false)}>Processo</a><a href="#sobre" onClick={()=>setMenuOpen(false)}>Sobre</a><a className="nav-contact" href={whatsappUrl} target="_blank" rel="noreferrer"><i className="bi bi-whatsapp"/>Conversar</a></nav><a className="header-cta" href={whatsappUrl} target="_blank" rel="noreferrer"><i className="bi bi-whatsapp"/><span>Conversar</span><i className="bi bi-arrow-up-right"/></a><button className="menu-toggle" aria-label={menuOpen?"Fechar menu":"Abrir menu"} aria-controls="navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}><i className={"bi "+(menuOpen?"bi-x-lg":"bi-list")}/></button></div></header>
  <section className="hero" id="inicio"><div className="hero-light"/><div className="hero-rule rule-one"/><div className="hero-rule rule-two"/><div className="hero-shell"><div className="hero-copy"><p className="hero-kicker"><span/>Design, tecnologia e presença</p><h1>Sua empresa merece ser <em>melhor percebida.</em></h1><p className="hero-description">Sites e sistemas pensados para transformar presença digital em confiança, profissionalismo e novas oportunidades.</p><div className="hero-actions"><a className="button primary" href={whatsappUrl} target="_blank" rel="noreferrer"><i className="bi bi-whatsapp"/>Conversar sobre um projeto<i className="bi bi-arrow-up-right"/></a><a className="button secondary" href="#projetos">Conhecer projetos<i className="bi bi-arrow-down"/></a></div></div><div className="hero-signature" aria-hidden="true"><span>Sites</span><span>Sistemas</span><span>Soluções digitais</span></div></div><a className="scroll-cue" href="#valor" aria-label="Continuar"><i className="bi bi-arrow-down"/></a></section>
  <section className="value section-shell" id="valor"><div className="value-lead"><Label>Presença com intenção</Label><h2>Não basta estar online.<br/><span>É preciso transmitir valor.</span></h2></div><div className="value-copy"><p>Antes de conversar com sua empresa, muita gente conhece a forma como ela se apresenta.</p><p>Uma experiência clara, profissional e própria ajuda o seu negócio a ocupar o espaço que merece.</p><a href="#projetos">Ver isso na prática <i className="bi bi-arrow-down-right"/></a></div></section>
  <section className="services section-shell" id="servicos"><div className="section-heading"><Label>O que eu desenvolvo</Label><h2>O digital certo para o que seu negócio precisa agora.</h2></div><div className="capability-grid">{capabilities.map(([icon,title,text],i)=><article key={title}><span>0{i+1}</span><i className={"bi "+icon}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="work" id="projetos"><div className="section-shell work-heading"><div><Label>Projetos reais</Label><h2>Uma identidade para cada negócio.</h2></div><p>Não existe uma aparência pronta para todos. Cada projeto encontra uma linguagem coerente com sua marca, seu público e seu objetivo.</p></div><div className="project-grid section-shell">{projects.map(p=><article className={"project "+p.tone} key={p.name}><a className="project-media" href={p.url} target="_blank" rel="noreferrer"><Image src={p.image} alt={"Logo oficial "+p.name} sizes="(max-width:700px) 90vw, 42vw"/><span><i className="bi bi-arrow-up-right"/></span></a><div className="project-info"><p>{p.type}</p><h3>{p.name}</h3><span>{p.text}</span><a href={p.url} target="_blank" rel="noreferrer">Conhecer projeto <i className="bi bi-box-arrow-up-right"/></a></div></article>)}</div></section>
  <section className="atlas section-shell"><div className="atlas-visual"><div className="partner-logo jp"><Image src={logoJp} alt="JPCreative" sizes="170px"/></div><span className="partner-x">×</span><div className="partner-logo"><Image src={logoAtlas} alt="Atlas" sizes="150px"/></div></div><div className="atlas-copy"><Label>JPCreative × Atlas</Label><p className="eyebrow">Sistema de atendimento</p><h2>Informação organizada. Atendimento mais simples.</h2><p>Sistema desenvolvido para centralizar informações e facilitar a rotina de atendimento, trazendo mais organização para processos que poderiam ficar dispersos.</p><a href="https://sites-project.joao081019pedrodasilv.workers.dev/" target="_blank" rel="noreferrer">Conhecer o sistema <i className="bi bi-arrow-up-right"/></a></div></section>
  <section className="process section-shell" id="processo"><div className="process-intro"><Label>Um processo simples</Label><h2>Você não precisa entender de tecnologia para começar.</h2><p>Me conte sobre o negócio e o que precisa mudar. A direção é construída a partir daí.</p></div><ol>{[["Conversamos","sobre momento, objetivo e necessidade."],["Definimos","a direção certa para o projeto."],["Desenvolvo","design e tecnologia em conjunto."],["Ajustamos","os detalhes com clareza."],["Publicamos","uma solução pronta para trabalhar."]].map(([title,text],i)=><li key={title}><span>0{i+1}</span><div><strong>{title}</strong><p>{text}</p></div><i className="bi bi-arrow-right"/></li>)}</ol></section>
  <section className="trust section-shell" id="sobre"><div className="about"><div className="about-logo"><Brand/></div><div><Label>Por trás da JPCreative</Label><h2>João Pedro da Silva</h2><p>Design, desenvolvimento e visão de negócio reunidos em projetos tratados com atenção do conceito ao detalhe final.</p><div className="social-links"><a href="https://www.linkedin.com/in/jo%C3%A3o-pedro-silva-380a1b32a" target="_blank" rel="noreferrer"><i className="bi bi-linkedin"/>LinkedIn<i className="bi bi-arrow-up-right"/></a><a href="https://github.com/JP081019" target="_blank" rel="noreferrer"><i className="bi bi-github"/>GitHub<i className="bi bi-arrow-up-right"/></a></div></div></div><div className="investment"><i className="bi bi-stars"/><p className="eyebrow">Qualidade compatível com o seu momento</p><h2>Profissional não precisa significar inacessível.</h2><p>Primeiro entendemos o que seu negócio realmente precisa. Assim, a solução pode ser coerente com o objetivo — sem obrigar você a contratar mais do que faz sentido agora.</p></div></section>
  <section className="final-cta section-shell" id="contato"><p className="eyebrow">Tem uma ideia — ou ainda está tentando entender o que precisa?</p><h2>Vamos conversar.</h2><p>A primeira conversa serve para conhecer seu negócio, sua necessidade e as possibilidades. Sem compromisso com uma solução antes da hora.</p><a className="button primary large" href={whatsappUrl} target="_blank" rel="noreferrer"><i className="bi bi-whatsapp"/>Conversar no WhatsApp<i className="bi bi-arrow-up-right"/></a></section>
  <footer><div className="section-shell footer-main"><div><Brand small/><p>Design, tecnologia e presença.</p></div><div><p>Navegação</p><a href="#servicos">Serviços</a><a href="#projetos">Projetos</a><a href="#processo">Processo</a></div><div><p>Contato</p><a href={whatsappUrl} target="_blank" rel="noreferrer"><i className="bi bi-whatsapp"/>WhatsApp</a><a href="https://instagram.com/jpcreative.dev" target="_blank" rel="noreferrer"><i className="bi bi-instagram"/>@jpcreative.dev</a><a href="mailto:joao081019p0edrodasilv@gmail.com"><i className="bi bi-envelope"/>E-mail</a></div></div><div className="section-shell footer-bottom"><span>© 2026 JPCreative</span><span>Santa Catarina · Brasil</span><a href="#inicio" aria-label="Voltar ao início"><i className="bi bi-arrow-up"/></a></div></footer>
 </main>
}
